name: PR
on:
  pull_request:
    types: [opened, reopened, edited, labeled, unlabeled, synchronize]

concurrency:
  group: pr-pre-commit-check-${{ github.ref }}
  cancel-in-progress: true

permissions:
  statuses: write
  contents: read
  checks: write
  pull-requests: read

jobs:
  pre_commmit:
    name: Pre-commit
    uses: dnlopes/Reusable.Workflows/.github/workflows/pre-commit-hooks.yaml@3f21ed54fec44904ebe737bb60a2a20d95767484 # v1.13.50
    secrets: inherit
